audit_header: false
title: "Washington DC's Best Real Estate Training"
description: Ryan Butler, a top Real Estate Agent in Washington DC, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
client:
  name: Ryan Butler
  title:
  license_number:
  about_markdown: |
    Ryan is one of the managing partner of Coalition Properties Group, a real estate team powered by Keller Williams Capital Properties. Joining the brokerage in 2016, Ryan was the 2017 Maryland/DC Regional Rookie of the Year. Since then, Ryan has continued to build out a top-producing real estate team, with top producing co-managing partners, Harrison Beacher (National Association of Realtors 30 Under 30 recipient) and Keith James (Real Trends award recipient ranked #13 out of 14,000 agents in the DC Metropolitan area). Coalition Properties Group's mission is the be the bridge to our community for all things real estate, lifestyle and wealth building.
  market: Washington DC
  brand: Coalition Properties Group
  brokerage: Keller Williams Capital Properties
  address: 519 C Street NE, Washington DC 20002
  phone: 202-813-8144
  phone_type:
  phone2:
  phone2_type:
  email: ryan@coalitionpg.com
  url: https://www.coalitionpg.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Coalition Properties Group can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/coalitionproperties/
  linkedin_url: https://www.linkedin.com/in/ryantrammellbutler/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/coalitionproperties/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Washington DC Real Estate Podcast with Ryan Butler'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Washington DC Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Coalition Properties Group - your professional Washington DC Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Washington DC, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Ryan Butler'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Washington DC Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
